import { Template } from 'meteor/templating';
import { ReactiveVar } from 'meteor/reactive-var';
import { FlowRouter } from 'meteor/ostrio:flow-router-extra';

import './main.html';
import './config/router.js';
import './layouts/blank';
import './layouts/blank.html';
import './pages/fraise-epreuve1';
import './pages/fraise-epreuve1.html';
import './pages/peche-epreuve1';
import './pages/peche-epreuve1.html';
import './pages/peche-epreuve2';
import './pages/peche-epreuve2.html';
import './pages/peche-epreuve3';
import './pages/peche-epreuve3.html';
import './pages/teams';
import './pages/teams.html';
import './pages/labo';
import './pages/labo.html';
import './pages/news';
import './pages/news.html';